Gradient of scalar-valued PhysicalFunction
bcube-project/Bcube.jl pull request #18
Opened 2023-12-01 20:44 UTC by bmxam

Here is a first answer to #16 , with an implementation of the gradient of a scalar-valued PhysicalFunction. So we can now write
```julia
using Bcube
using LinearAlgebra
mesh = one_cell_mesh(:quad)
U = TrialFESpace(FunctionSpace(:Lagrange, 1), mesh; size = 2)
V = TestFESpace(U)
f = PhysicalFunction(x -> 1.0) # scalar-valued function
dΩ = Measure(CellDomain(mesh), 1)
assemble_linear(v -> ∫(∇(f) ⋅ v)dΩ, V)
```

**however**, the present development won't work for a vector-valued `PhysicalFunction` because we shall then use `ForwardDiff.jacobian` instead of `ForwardDiff.gradient`. But to do so, we need to add a `size` attribute (or a type-parameter) to `CellFunction`. Let's do this in a second PR.

misc : I have also increased the Project version, and updated the documentation to close #17

2023-12-04 11:38 UTC, ghislainb requested changes

2023-12-04 11:38 UTC, ghislainb commented on test/operator/test_algebra.jl
> +        translate!(mesh, rand(2)) # `rand` to check that the ref->phys mapping is effective
I think it would be better to avoid using `rand` in tests when possible

2023-12-04 11:38 UTC, ghislainb commented on src/assembler/assembler.jl
> +When integrating the constant function `x -> PhysicalFunction(1)`, the sum of this
You probably mean: `PhysicalFunction(x -> 1)`

2023-12-10 20:43 UTC, bmxam commented on test/operator/test_algebra.jl
> +        translate!(mesh, rand(2)) # `rand` to check that the ref->phys mapping is effective
I don't really share your opinion, here `rand` is used as the mathematical operator `∀` : the test should always work. But I don't really mind so I've followed your suggestion.

2023-12-10 20:43 UTC, bmxam commented on src/assembler/assembler.jl
> +When integrating the constant function `x -> PhysicalFunction(1)`, the sum of this
good point

2023-12-10 21:11 UTC, ghislainb approved these changes

2023-12-10 21:11 UTC, merged