Addition of multiplierFESpace
bcube-project/Bcube.jl pull request #37
Opened 2024-01-23 18:54 UTC by lokmanb

This PR introduces a first development of MultiplierFESpace for the solution of constrained minimization problems. The idea is to be able to construct a MultiFESpace combining the usual finite element discretization on the one hand and Lagrange multipliers on the other. Here the Lagrange multipliers are additional unknowns and the MultiFESpace combined with MultiplierFESpace enables to assemble a global system which yields the solution of the constrained minimization problem as well as the associated Lagrange multipliers. The development is built on the constrained Poisson example.

2024-01-29 11:46 UTC, bmxam commented on src/fespace/fespace.jl
> +    ndofs = ones(ncells(mesh), size) # Temporary allocation for development purposes
can you remove the comment since it seems that we finally kept this line

2024-01-29 11:52 UTC, bmxam commented on src/assembler/assembler.jl
> +"""
Can you please merge the three `_count_n_elts` doc strings into a unique one, located at the top of the first method declaration? Take a look at `src/fespace/fespace.jl` -> `TrialFESpace` constructor for inspiration.

2024-01-29 11:53 UTC, bmxam requested changes
We need some unit tests, especially on the dofhandler for the MultiplierFESpace. Maybe some tests taken from the tutorial configuration?

Moreover, a "global" test like Ghislain did for the DG Poisson would be nice. We can do it together during a live session.

2024-02-15 22:03 UTC, lokmanb commented
Thanks for the review. I added a few unit tests for MultiplierFESpace. Concerning the "global" test, did you mean a test at the end of the corresponding example (with the error computation)?

2024-02-16 15:16 UTC, bmxam commented
> Thanks for the review. I added a few unit tests for MultiplierFESpace. Concerning the "global" test, did you mean a test at the end of the corresponding example (with the error computation)?

I meant encapsulating your whole example (or a simplified version) into a `@testset` with some kind of test at the end (on the error for instance). Like it is done here for the Poisson DG : https://github.com/bcube-project/Bcube.jl/blob/d81437d097f86e5baa993c4eec45afca880d04fb/test/dof/test_assembler.jl#L213

2024-02-24 22:49 UTC, bmxam approved these changes

2024-02-25 10:25 UTC, ghislainb approved these changes

2024-02-25 10:25 UTC, ghislainb commented on src/fespace/fespace.jl
> +    ndofs = ones(ncells(mesh), size) # Temporary allocation for development purposes
`Ones` or `Fill` from `FillArrays.jl` could be considered

2024-02-25 10:25 UTC, ghislainb commented on src/fespace/fespace.jl
> +    ndofs = ones(ncells(mesh), size) # Temporary allocation for development purposes
I suggest to update this comment: "TODO : use a `Fill` array to save memory space"

2024-02-25 10:25 UTC, merged